name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild -project Droplet.xcodeproj -scheme Droplet -configuration Debug build | xcpretty
    - name: Run tests
      run: xcodebuild -project Droplet.xcodeproj -scheme Droplet -configuration Debug test | xcpretty
